---
- name: Install Apigee component Monit
  command: '/opt/apigee/apigee-service/bin/apigee-service apigee-monit install'

- name: Configure Apigee component Monit
  command: '/opt/apigee/apigee-service/bin/apigee-service apigee-monit configure'

- name: Start Apigee component Monit
  command: '/opt/apigee/apigee-service/bin/apigee-service apigee-monit start'

- name: Auto-Start Apigee component Monit
  become: yes
  copy:
    src: /opt/apigee/apigee-monit/cron/apigee-monit.cron
    dest: /etc/cron.d
    remote_src: yes
